### ISSUE TITLE
missing addstruct

### ISSUE THREAD

**Issue by harrisonritz** [jdiedrichsen/pcm_toolbox#10]
line 265 of `pcm_fitModelIndividCrossval` calls `addstruct`, which is a custom function not in the repo.

**Comment by jdiedrichsen** [comment]
sorry - it's part of the jdiedrichsen/dataframe toolbox - for now you can download that repository - I will make sure that next release does not have that dependency anymore

**Comment by harrisonritz** [comment]
thanks!
