### ISSUE TITLE
General questions about pcm_EM

### ISSUE THREAD

**Issue by lyambailey** [jdiedrichsen/pcm_toolbox#13]
Dear contributors,

I am trying to perform pattern component modelling on a single dataset to estimate U, as in Diedrichsen, J., Ridgway, G., Friston, K.J., Wiestler, T., (2011). I believe that the pcm_EM function is the simplest way to do this, however I have a couple of questions about its implementation...

1. pcm_EM calls a custom function 'ML_constrained_fast', which is not included in the toolbox. Was 'ML_constrained_fast' replaced?
2. I would like to subtract out common activation. I believe this is achieved by specifying a fixed effects matrix X. How should X be defined / structured?

Full reference: Diedrichsen, J., Ridgway, G., Friston, K.J., Wiestler, T., (2011). Comparing the similarity and spatial structure of neural representations: A pattern-component model. Neuroimage.

**Comment by jdiedrichsen** [comment]
Hi  Liam, 

1. pcm_EM is not actively supported anymore, as it is much slower than pcm_NR. If you want to estimate the U s (regressors for the features), you can use 
```
[T,theta]=pcm_fitModelIndivid(Y,Model,part_vec,cond_vec)
pcm_estimateU(Model,theta,Y)
``` 
If you don't want to have the complications (and extra features) of a PCM model, you may find it easier to use the mixed (regression) model: 
```
[theta_hat,INFO]=pcm_fitModelRegression(Z,Y,comp,X)
[U, varU] = pcm_estimateRegression(Z,Y,comp,X,theta_hat)
```
I have updated the documentation for the latter two functions in the latest commit. 

2.  Yes- the fixed effects normally include the intercept. Either one intercept overall (a vector of ones), or an intercept per imaging run (a column per run - with 1 for the run and 0 elsewhere).

Hope that helps

**Comment by lyambailey** [comment]
Hi @jdiedrichsen

Thanks very much - I think the mixed regression is exactly what I need. 

I just have one follow-up question about `pcm_estimateRegression`. The documentation states that the `comp` argument requires "Indicator (1..K) of which regressor belongs to which regressor group".

Assuming I have data `Y` with 3 unique stimuli repeated across 2 runs, arranged in the following manner:

```
stim1 run1
stim2 run1
stim3 run1 
stim1 run2 
stim2 run2
stim3 run2
```

then my design matrix `Z` would look like this:

```
1 0 0
0 1 0
0 0 1
1 0 0
0 1 0
0 0 1
```

Should `comp` simply be `[1, 2, 3]` ?

Thanks!

**Comment by jdiedrichsen** [comment]
Yes - Setting comp to [1,2,3] estimates different variance coefficients for all three. Setting comp to [1,2,2] would force the 2nd and 3rd to have the same variance coefficient (regularization), but of course they still would have different U's (regression coefficients). Classical example would be to have 8 different regressors that indicate different movement directions. The single variance parameter would indicate how strong movement direction overall is encoded (independent of which direction). 
Makes sense?

**Comment by lyambailey** [comment]
Yes, that makes sense to me. Thank you very much for the help!
